### ISSUE TITLE
SDK Üzerinde Prod ve Beta Ortamının Hazırlanması

### ISSUE THREAD

**Issue by salyangoz** [salyangoz/fideas-sdk#4]
- [ ] SDK üzerinde prod ve beta ortamının linklerinin base URL'e bağlanması gerekiyor. Bir configuration ile prod ve test ortamına geçebilmeli ve bu geçiş sayesinde web servis base url'i değişeceğini söyleyeyim. Bu sebeple kodda base url kurgusu olmalı. Şuan da tüm url'ler çakılı olarak duruyor. Buna bir config dosyası oluşturulup base url'den türetilmesi gerekli.

**Comment by necroshine** [comment]
Bununla ilgilli gelistirme BaseUrl gelistirmesi ile saglandi

**Comment by salyangoz** [comment]
@necroshine Test ve Prod olarak ayırdık mı baseURL'i o çok önemli Debug çıkarttığında Test Release çıkarttığında Prod url'i kullanması gerekiyor.

**Comment by necroshine** [comment]
@salyangoz bunu sdk tarafinda degil de app tarafindan yapmak daha mantikli sdk yapisinin ne uzerinde calistigini bilmesine gerek yok bunu app tarafindan gonderilecek urlden belirlemek herzaman daha mantiklidir. orada debug release yapisini kullaniriz.

**Comment by salyangoz** [comment]
Anlaştık.
