### ISSUE TITLE
URL'lerin Base URL olarak oluşturulması

### ISSUE THREAD

**Issue by salyangoz** [salyangoz/fideas-sdk#5]
- [ ] URL'lerin Base URL olarak düzenlenmesi gerekiyor. 
https://github.com/salyangoz/fideas-sdk/blob/943627a0df60d8e8720c006e8eb6f592dc827875/FideasLib/FideaConnector.swift#L31

**Comment by necroshine** [comment]
Bu static url tanimlamasi kaldirildi onun yerine SDK nin ana sinifi yaratilirken application icinden bu urlin tanimlanmasi saglandi.
