### ISSUE TITLE
Soap Kütüphanesi Kullanılması

### ISSUE THREAD

**Issue by salyangoz** [salyangoz/fideas-sdk#6]
- [ ] Request'lerin atılabilmesi için SOAP kütüphanesi kullanalım. Bu şekilde hem okunabilirliği, hem yazma maliyeti artıyor. Kütüphane ile daha düzenli bir request atabiliriz.

https://github.com/salyangoz/fideas-sdk/blob/943627a0df60d8e8720c006e8eb6f592dc827875/FideasLib/FideaConnector.swift#L36

**Comment by necroshine** [comment]
Bununla ilgili bir kutuphane bulundu fakat adamlarin xml yapisina uymadigi icin vazgecildi bunun yerine kendi xmlrequestlerimizi yaratan bir sinif yaratip islemleri onun uzerinden yapmaya basladikk
